cfg_name: 'default'

# dataset
raw_base_dir: '/data/Sintel/training/albedo'
prepared_base_dir: '/local_data_2/dahye/UnOpticalFlow/sintel_release'
gt_2012_dir: '/data/KITTI12/training'
gt_2015_dir: '/data/KITTI15/training'
static_frames_txt: '/home/dahye/UnOpticalFlow/data/eigen/static_frames.txt'
test_scenes_txt: '/home/dahye/UnOpticalFlow/data/eigen/test_scenes.txt'
dataset: 'sintel_raw'
num_scales: 3
stride: 2

# training
num_iterations: 200000

# loss hyperparameters
w_ssim: 0.85 # w_pixel = 1 - w_ssim
w_flow_smooth: 6.0
w_flow_consis: 0.01

h_flow_consist_alpha: 3.0
h_flow_consist_beta: 0.05


# basic info
# img_hw: [448, 1024]
img_hw: [384, 832]
use_svd_gpu: False

